"""superuser

Revision ID: 29c5bf35d0a0
Revises: 8c1c40330bf3
Create Date: 2021-05-21 11:40:23.150325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c5bf35d0a0'
down_revision = '8c1c40330bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.alter_column('users', 'name', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('users', 'password', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('users', 'name', existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
