"""add_props

Revision ID: 4588e64f8cb5
Revises: aca9c8214478
Create Date: 2021-06-02 09:07:51.820575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4588e64f8cb5'
down_revision = 'aca9c8214478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uoe_course', 'description',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('uoe_course', 'background_color',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uoe_course', 'background_color',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('uoe_course', 'description',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
