"""number_user_and_date

Revision ID: aca9c8214478
Revises: b44df0e9f325
Create Date: 2021-05-23 17:00:11.157579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca9c8214478'
down_revision = 'b44df0e9f325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'number')
    # ### end Alembic commands ###
