"""create exercises

Revision ID: dc9e65e4f05b
Revises: 4588e64f8cb5
Create Date: 2021-06-07 08:24:34.053418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9e65e4f05b'
down_revision = '4588e64f8cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uoe_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('discriminator', sa.String(length=50), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['uoe_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uoe_exercise_id'), 'uoe_exercise', ['id'], unique=False)
    op.create_table('uoe_kw_transformation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['uoe_exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uoe_open_cloze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['uoe_exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uoe_open_cloze')
    op.drop_table('uoe_kw_transformation')
    op.drop_index(op.f('ix_uoe_exercise_id'), table_name='uoe_exercise')
    op.drop_table('uoe_exercise')
    # ### end Alembic commands ###
