"""generics

Revision ID: f7651a0880cd
Revises: dc9e65e4f05b
Create Date: 2021-06-10 07:36:49.242279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7651a0880cd'
down_revision = 'dc9e65e4f05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uoe_open_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['uoe_exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uoe_open_space_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=128), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['uoe_open_space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uoe_open_space_solution_id'), 'uoe_open_space_solution', ['id'], unique=False)
    op.create_table('uoe_word_formation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['uoe_open_space.id'], name='fk_word_formation_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('uoe_open_cloze_id_fkey', 'uoe_open_cloze', type_='foreignkey')
    op.create_foreign_key('fk_open_cloze_id', 'uoe_open_cloze', 'uoe_open_space', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_open_cloze_id', 'uoe_open_cloze', type_='foreignkey')
    op.create_foreign_key('uoe_open_cloze_id_fkey', 'uoe_open_cloze', 'uoe_exercise', ['id'], ['id'])
    op.drop_table('uoe_word_formation')
    op.drop_index(op.f('ix_uoe_open_space_solution_id'), table_name='uoe_open_space_solution')
    op.drop_table('uoe_open_space_solution')
    op.drop_table('uoe_open_space')
    # ### end Alembic commands ###
